ZHJ.PerfectOA.WebApp/Controllers/ActionInfoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZHJ.PerfectOA.Model;
using ZHJ.PerfectOA.Model.Enum;

namespace ZHJ.PerfectOA.WebApp.Controllers
{
    public class ActionInfoController : Controller
    {
        //
        // GET: /ActionInfo/
        IBLL.IActionInfoService ActionInfoService { get; set; }
        IBLL.IRoleInfoService RoleInfoService { get; set; }

        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 分页展示数据
        /// </summary>
        /// <returns></returns>
        public ActionResult GetActionInfo()
        {
            int pageIndex = Request["page"] != null ? int.Parse(Request["page"]) : 1;
            int pageSize = Request["rows"] != null ? int.Parse(Request["rows"]) : 5;
            int totalCount;
            short delFlag = (short)DelFlags.Normal;
            var actionInfoList = ActionInfoService.LoadPageEntities<int>(pageIndex, pageSize, out totalCount, c => c.DelFlag == delFlag, c => c.ID, true);
            var temp = from r in actionInfoList
                       select new { ID = r.ID, ActionInfoName = r.ActionInfoName, Sort = r.Sort, Remark = r.Remark, SumTime = r.SubTime, Url = r.Url, HttpMethod = r.HttpMethod, ActionTypeEnum = r.ActionTypeEnum };
            return Json(new { rows = temp, total = totalCount }, JsonRequestBehavior.AllowGet);

        }

        /// <summary>
        /// 上传图片
        /// </summary>
        /// <returns></returns>
        public ActionResult FileUpload()
        {
            HttpPostedFileBase file = Request.Files["fileImage"];
            if (file != null)
            {
                string fileName = Path.GetFileName(file.FileName);
                string fileExt = Path.GetExtension(fileName);
                if (fileExt == ".jpg")
                {
                    string dir = "/ImageFileUp/" + DateTime.Now.Year + "/" + DateTime.Now.Month + "/" + DateTime.Now.Day + "/";
                    Directory.CreateDirectory(Path.GetDirectoryName(Request.MapPath(dir)));
                    string newfileName = Guid.NewGuid().ToString();
                    string fullDir = dir + newfileName + fileExt;
                    file.SaveAs(Request.MapPath(fullDir));
                    return Content("ok:" + fullDir);
                }
                else
                {
                    return Content("no:文件类型错误!!");
                }
            }
            else
            {
                return Content("no:文件不能为空");
            }
        }

        /// <summary>
        /// 删除操作
        /// </summary>
        /// <returns></returns>
        public ActionResult DeleteActionInfo()
        {
            //分割id字符串 将每个id加到list集合中
            string strId = Request["strId"];
            string[] ids = strId.Split(',');
            List<int> list = new List<int>();
            foreach (var id in ids)
            {
                list.Add(int.Parse(id));
            }

            if (ActionInfoService.DeleteEntities(list))
            {
                return Content("ok");
            }
            else
            {
                return Content("no");
            }
        }

        /// <summary>
        /// 添加权限方法
        /// </summary>
        /// <param name="actionInfo"></param>
        /// <returns></returns>
        public ActionResult AddActionInfo(ActionInfo actionInfo)
        {
            actionInfo.DelFlag = 0;
            actionInfo.ModifiedOn = DateTime.Now.ToString();
            actionInfo.SubTime = DateTime.Now;
            actionInfo.Url = actionInfo.Url.ToLower();
            ActionInfoService.AddEntity(actionInfo);
            return Content("ok");
        }

        /// <summary>
        /// 修改要显示的角色信息
        /// </summary>
        /// <returns></returns>
        public ActionResult ShowEditInfo()
        {
            int id = int.Parse(Request["id"]);
            ActionInfo actionInfo = ActionInfoService.LoadEntities(a => a.ID == id).FirstOrDefault();
            ViewData.Model = actionInfo;
            return View();
        }

        /// <summary>
        /// 保存修改之后的信息
        /// </summary>
        /// <returns></returns>
       [HttpPost]
        public ActionResult ShowEditInfo(ActionInfo actionInfo)
        {
            actionInfo.DelFlag = 0;

            if (ActionInfoService.EditEntity(actionInfo))
            {
                return Content("ok");
            }
            else
            {
                return Content("no");
            }
        }

        /// <summary>
        /// 给权限分配角色
        /// </summary>
        /// <returns></returns>
       public ActionResult SetActionRoleInfo()
       {
           int id = int.Parse(Request["id"]);//权限编号.
           var actionInfo = ActionInfoService.LoadEntities(a => a.ID == id).FirstOrDefault();
           ViewBag.ActionInfo = actionInfo;
           short delFlag = (short)DelFlags.Normal;
           ViewBag.AllRoleList = RoleInfoService.LoadEntities(r => r.DelFlag == delFlag).ToList();//获取所有的角色.
           ViewBag.AllRoleIdList = (from r in actionInfo.RoleInfo
                                    select r.ID).ToList();
           return View();

       }

       [HttpPost]
       public ActionResult SetActionRoleInfo(ActionInfo actionInfo)
       {
           int actionId = int.Parse(Request["actionId"]);
           string[] AllKeys = Request.Form.AllKeys;
           List<int> list = new List<int>();
           foreach (string key in AllKeys)
           {
               if (key.StartsWith("cba_"))
               {
                   string k = key.Replace("cba_", "");
                   list.Add(int.Parse(k));
               }
           }
           if (ActionInfoService.SetActionInfoRole(actionId, list))
           {
               return Content("ok");
           }
           else
           {
               return Content("no");
           }
       }
    }
}

ZHJ.PerfectOA.WebApp/Views/ActionInfo/SetActionRoleInfo.cshtml
@{
    Layout = null;
}
@using ZHJ.PerfectOA.Model
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SetActionRoleInfo</title>
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

    <script>
        function subForm() {
            $("#addRoleForm").submit();
        }
        function afterAdd(data) {
            if (data=="ok") {
                window.parent.afterSetRoleq();
            }
            
        }
    </script>
</head>
<body>
    为
    @{
        ActionInfo actionInfo = ViewBag.ActionInfo;
        <span style="font-size:16px;color:red">@actionInfo.ActionInfoName</span>
    }权限分配角色
    @using (Ajax.BeginForm("SetActionRoleInfo", "ActionInfo", new { }, new AjaxOptions() { HttpMethod = "post", OnSuccess = "afterAdd" }, new { id = "addRoleForm" }))
    {
        <input type="hidden" name="actionId" value="@actionInfo.ID" />
        List<RoleInfo> AllRoleList = ViewBag.AllRoleList;
        List<int> AllRoleIdList = ViewBag.AllRoleIdList;
        foreach (RoleInfo roleInfo in AllRoleList)
        {
            string roleName = "cba_" + roleInfo.ID;
            if (AllRoleIdList.Contains(roleInfo.ID))
            {
                <input type="checkbox" checked="checked" name="@roleName" value="@roleInfo.ID" />@roleInfo.RoleName
            }
            else
            {
                <input type="checkbox" name="@roleName" value="@roleInfo.ID" />@roleInfo.RoleName
            }
        }
    }






</body>
</html>

ZHJ.PerfectOA.WebApp/Views/ActionInfo/ShowEditInfo.cshtml
@model ZHJ.PerfectOA.Model.ActionInfo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowEditInfo</title>
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script type="text/javascript">
        
        $(function () {
            $("#btnClear").click(function () {
                $("#div1").html("");
            });

            
        });
    </script>

</head>
<body>

    
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
    
        <fieldset>
            <legend>ActionInfo</legend>
    
            @Html.HiddenFor(model => model.ID)
    
            <div class="editor-label">
                @Html.LabelFor(model => model.SubTime)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.SubTime)
                @Html.ValidationMessageFor(model => model.SubTime)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.DelFlag)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.DelFlag)
                @Html.ValidationMessageFor(model => model.DelFlag)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.ModifiedOn)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.ModifiedOn)
                @Html.ValidationMessageFor(model => model.ModifiedOn)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Remark)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Remark)
                @Html.ValidationMessageFor(model => model.Remark)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Url)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Url)
                @Html.ValidationMessageFor(model => model.Url)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.HttpMethod)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.HttpMethod)
                @Html.ValidationMessageFor(model => model.HttpMethod)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.ActionMethodName)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.ActionMethodName)
                @Html.ValidationMessageFor(model => model.ActionMethodName)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.ControllerName)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.ControllerName)
                @Html.ValidationMessageFor(model => model.ControllerName)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.ActionInfoName)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.ActionInfoName)
                @Html.ValidationMessageFor(model => model.ActionInfoName)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Sort)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Sort)
                @Html.ValidationMessageFor(model => model.Sort)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.ActionTypeEnum)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.ActionTypeEnum)
                @Html.ValidationMessageFor(model => model.ActionTypeEnum)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.MenuIcon)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.MenuIcon)
                @Html.ValidationMessageFor(model => model.MenuIcon)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.IconWidth)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.IconWidth)
                @Html.ValidationMessageFor(model => model.IconWidth)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.IconHeight)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.IconHeight)
                @Html.ValidationMessageFor(model => model.IconHeight)
            </div>
    
            <p>
                <input type="button" id="btn" value="Save" />
            </p>
        </fieldset>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>