ZHJ.PerfectOA.WebApp/Controllers/UserInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZHJ.PerfectOA.Model.Enum;
using ZHJ.PerfectOA.Model;

namespace ZHJ.PerfectOA.WebApp.Controllers
{
    public class UserInfoController : Controller
    {
        //
        // GET: /UserInfo/
        //IBLL.IUserInfoService UserInfoServer = new BLL.UserInfoService();
        IBLL.IUserInfoService UserInfoService { get; set; }
        IBLL.IRoleInfoService RoleInfoService { get; set; }
        IBLL.IActionInfoService ActionInfoService { get; set; }
        IBLL.IR_UserInfo_ActionInfoService R_UserInfo_ActionInfoService { get; set; }

        public ActionResult Index()
        {
            return View();
        }

        #region 分页显示用户信息数据
        /// <summary>
        /// 分页获取数据
        /// </summary>
        /// <returns></returns>
        public ActionResult GetUserInfo()
        {
            int pageIndex = Request["page"] != null ? int.Parse(Request["page"]) : 1;
            int pageSize = Request["rows"] != null ? int.Parse(Request["rows"]) : 5;
            int totalCount;
            short delflage = (short)DelFlags.Normal;
            var userInfoList = UserInfoService.LoadPageEntities<int>(pageIndex, pageSize, out totalCount, c => c.DelFlag == delflage, c => c.ID, true);
            var temp = from u in userInfoList
                       select new { ID = u.ID, UserName = u.UName, UserPass = u.UPwd, Remark = u.Remark, RegTime = u.SubTime };
            //将数据JSON化之后返回客户端，并且制定是来自客户端的Get请求方法的
            return Json(new { rows = temp, total = totalCount }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region 添加用户操作
        /// <summary>
        /// 添加用户操作
        /// </summary>
        /// <returns></returns>
        public ActionResult AddUserInfo(UserInfo userinfo)
        {
            //将数据补充完整
            userinfo.DelFlag = 0;
            userinfo.SubTime = DateTime.Now;
            userinfo.ModifiedOn = DateTime.Now;
            //将补充完整的数据提交到BLL
            UserInfoService.AddEntity(userinfo);
            //成功之后返回OK
            return Content("ok");
        }
        #endregion

        #region 删除操作
        /// <summary>
        /// 删除操作
        /// </summary>
        /// <returns></returns>
        public ActionResult DeleteUserInfo()
        {
            //分割id字符串 将每个id加到list集合中
            string strId = Request["strId"];
            string[] ids = strId.Split(',');
            List<int> list = new List<int>();
            foreach (var id in ids)
            {
                list.Add(int.Parse(id));
            }

            if (UserInfoService.DeleteEntities(list))
            {
                return Content("ok");
            }
            else
            {
                return Content("no");
            }
        }
        #endregion

        #region 修改操作---获取要修改的信息
        /// <summary>
        /// 修改操作---获取要修改的信息
        /// </summary>
        /// <returns></returns>
        public ActionResult GetUserInfoModel()
        {
            int id = int.Parse(Request["id"]);
            UserInfo userinfo = UserInfoService.LoadEntities(u => u.ID == id).FirstOrDefault();

            return Json(userinfo, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region 修改用户信息
        /// <summary>
        /// 修改用户信息
        /// </summary>
        /// <param name="userinfo"></param>
        /// <returns></returns>
        public ActionResult EditUserInfo(UserInfo userinfo)
        {
            userinfo.DelFlag = 0;
            userinfo.ModifiedOn = DateTime.Now;
            if (UserInfoService.EditEntity(userinfo))
            {
                return Content("ok");
            }
            else
            {
                return Content("no");
            }
        }
        #endregion

        #region 展示和修改用户的角色信息
        /// <summary>
        /// 展示用户的角色信息
        /// </summary>
        /// <returns></returns>
        public ActionResult SetUserRoleInfo()
        {
            int userId = int.Parse(Request["id"]);
            var userInfo = UserInfoService.LoadEntities(u => u.ID == userId).FirstOrDefault();
            ViewBag.UserInfo = userInfo;
            //获取所有的角色信息
            short delFlag = (short)DelFlags.Normal;
            var AllRole = RoleInfoService.LoadEntities(r => r.DelFlag == delFlag).ToList();
            //当用户已经具有的角色
            var AllExtRoleId = (from r in userInfo.RoleInfo
                                select r.ID).ToList();
            ViewBag.AllRole = AllRole;
            ViewBag.AllRoleId = AllExtRoleId;
            return View();
        }

        /// <summary>
        /// 给用户分配角色信息
        /// </summary>
        /// <param name="roleInfo"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SetUserRoleInfo(RoleInfo roleInfo)
        {
            int userId = int.Parse(Request["userId"]);
            //获取所有表单中的元素
            string[] allKeys = Request.Form.AllKeys;
            List<int> list = new List<int>();
            foreach (string key in allKeys)
            {
                //获取包含name包含cha_的值
                if (key.StartsWith("cba_"))
                {
                    string k = key.Replace("cba_", "");
                    list.Add(int.Parse(k));
                }
            }
            if (UserInfoService.SetUserInfoRole(userId, list))
            {
                return Content("ok");
            }
            else
            {
                return Content("no");
            }
        }
        #endregion


        #region 为特殊用户分配权限
        /// <summary>
        /// 为特殊用户分配权限-渲染模板
        /// </summary>
        /// <returns></returns>
        public ActionResult SetUserActionInfo()
        {
            int userId = int.Parse(Request["userId"]);
            var userInfo = UserInfoService.LoadEntities(u => u.ID == userId).FirstOrDefault();
            ViewData.Model = userInfo;
            ViewBag.AllActionInfo = ActionInfoService.LoadEntities(a => true).ToList();
            ViewBag.AllActionId = userInfo.R_UserInfo_ActionInfo.ToList();//该用户具有的权限
            return View();
        }
        /// <summary>
        /// 为特殊用户分配权限-操作
        /// </summary>
        /// <param name="userInfo"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SetUserActionInfo(UserInfo userInfo)
        {
            int userId = int.Parse(Request["userId"]);
            int actionId = int.Parse(Request["actionId"]);
            bool value = Request["value"] == "true" ? true : false;
            if (R_UserInfo_ActionInfoService.SetUserInfoActionInfo(userId, actionId, value))
            {
                return Content("ok");
            }
            else
            {
                return Content("no");
            }
        }

        /// <summary>
        /// 清除用户的权限
        /// </summary>
        /// <returns></returns>
        public ActionResult RemoveUserAction()
        {
            int userId = int.Parse(Request["userId"]);
            int actionId = int.Parse(Request["actionId"]);
            var r_userInfo_actionInfo = R_UserInfo_ActionInfoService.LoadEntities(r => r.UserInfoID == userId && r.ActionInfoID == actionId).FirstOrDefault();
            if (R_UserInfo_ActionInfoService.DeleteEntity(r_userInfo_actionInfo))
            {
                return Content("ok");
            }
            else
            {
                return Content("no");
            }

        }
        #endregion
        
    }
}

ZHJ.PerfectOA.WebApp/Views/UserInfo/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/themes/default/easyui.css" rel="stylesheet" />
    <link href="~/Content/themes/icon.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery.easyui.min.js"></script>
    <script src="~/Scripts/easyui-lang-zh_CN.js"></script>
    <script src="~/Scripts/datapattern.js"></script>

    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

    <script>
        $(function () {
            $('#divAdd').css('display', 'none');
            $("#divEdit").css("display", "none");
            //加载数据
            loadData();
        })

        //分页加载数据
        function loadData() {
            $('#tt').datagrid({
                url: '/UserInfo/GetUserInfo',
                title: '用户数据表格',
                width: 700,
                height: 400,
                fitColumns: true, //列自适应
                nowrap: false,
                idField: 'ID',//主键列的列明
                loadMsg: '正在加载用户的信息...',
                pagination: true,//是否有分页
                singleSelect: false,//是否单行选择
                pageSize: 5,//页大小，一页多少条数据
                pageNumber: 1,//当前页，默认的
                pageList: [5, 10, 15],
                queryParams: {},//往后台传递参数
                columns: [[//c.UserName, c.UserPass, c.Email, c.RegTime
                    { field: 'ck', checkbox: true, align: 'left', width: 50 },
					{ field: 'ID', title: '编号', width: 80 },
					{ field: 'UserName', title: '姓名', width: 120 },
                     { field: 'UserPass', title: '密码', width: 120 },
                      { field: 'Remark', title: '备注', width: 120 },
					{
					    field: 'RegTime', title: '时间', width: 80, align: 'right',
					    formatter: function (value, row, index) {
					        return (eval(value.replace(/\/Date\((\d+)\)\//gi, "new Date($1)"))).pattern("yyyy-M-d");
					    }
					}
                ]],
                toolbar: [{
                    id: 'btnDelete',
                    text: '删除',
                    iconCls: 'icon-remove',
                    handler: function () {
                        deleteInfo();
                    }
                }, {
                    id: 'btnAdd',
                    text: '添加',
                    iconCls: 'icon-add',
                    handler: function () {
                        addInfo();
                    }
                }, {
                    id: 'btnEdit',
                    text: '编辑',
                    iconCls: 'icon-edit',
                    handler: function () {
                        editInfo();
                    }
                }, {
                    id: 'btnSetUserRole',
                    text: '为用户分配角色',
                    iconCls: 'icon-edit',
                    handler: function () {
                        setUserRoleInfo();
                    }
                },{
                    id: 'btnSetUserAction',
                    text: '为特殊用户分配权限',
                    iconCls: 'icon-edit',
                    handler: function () {
                        setUserActionInfo();
                    }
                }]
            });
        }


        //为特殊用户分配权限-渲染数据模板
        function setUserActionInfo() {
            var rows = $('#tt').datagrid('getSelections');
            if (rows.length != 1) {
                $.messager.alert("提醒", "分配权限只能选择一人!", "error");
                return;
            }
            $("#setActionFrame").attr("src", "/UserInfo/SetUserActionInfo/?userId=" + rows[0].ID);
            $("#setActionDiv").css("display", "block");
            $('#setActionDiv').dialog({
                title: "添加信息",
                collapsible: true,
                width: 600,
                height: 400,
                modal: true,
                resizable: true,
                buttons: [{
                    text: 'Ok',
                    iconCls: 'icon-ok',
                    handler: function () {
                        //提交表单
                        $('#setActionDiv').dialog('close');
                    }
                }, {
                    text: 'Cancel',
                    handler: function () {
                        $('#setActionDiv').dialog('close');
                    }
                }]
            });
        }





        //为用户分配角色
        function setUserRoleInfo() {
            var rows = $('#tt').datagrid('getSelections');
            if (rows.length != 1) {
                $.messager.alert("提醒", "必须一次只能选一个!", "error");
                return;
            }
            $("#setRoleFrame").attr("src", "/UserInfo/SetUserRoleInfo/?id=" + rows[0].ID);
            $("#setRoleDiv").css("display", "block");
            $('#setRoleDiv').dialog({
                title: "为用户分配角色信息",
                collapsible: true,
                width: 300,
                height: 400,
                modal: true,
                resizable: true,
                buttons: [{
                    text: '确定',
                    iconCls: 'icon-ok',
                    handler: function () {
                        //提交表单
                        var childWindow = $("#setRoleFrame")[0].contentWindow;//获取子窗体的window对象.
                        childWindow.subForm();//调用子窗体中的subForm方法.
                    }
                }, {
                    text: '取消',
                    handler: function () {
                        $('#setRoleDiv').dialog('close');
                    }
                }]
            });
        }
        //关闭分配角色的窗口
        function afterSetUserRole() {
            $('#setRoleDiv').dialog('close');
        }


        //添加数据，显示添加窗口
        function addInfo() {
            $("#divAdd").css("display", "block");
            $('#divAdd').dialog({
                title: "添加信息",
                collapsible: true,
                width: 300,
                height: 200,
                modal: true,
                resizable: true,
                buttons: [{
                    text: '确定',
                    iconCls: 'icon-ok',
                    handler: function () {
                        //提交表单
                        $("#addForm").submit();
                    }
                }, {
                    text: '取消',
                    handler: function () {
                        $('#divAdd').dialog('close');
                    }
                }]
            });

        }
        //单机添加按钮之后 执行添加操作
        function afterAdd(data) {
            if (data == 'ok') {
                //关闭添加窗口
                $('#divAdd').dialog('close');
                //清空表单中的数据
                $('#addForm input').val('');
                loadData();
            }
        }

        //删除操作
        function deleteInfo() {
            var rows = $('#tt').datagrid('getSelections');
            //如果没有选中要删除的记录
            if (rows.length == 0 || !rows) {
                $.messager.alert('提醒', '请选择要删除的记录!', 'error');
                return;
            }
            $.messager.confirm('提示', '确定要删除么?', function (r) {
                //r代表了用户点击的操作，TRUE代表了确定，FALSE代表了取消
                if (r) {
                    var strId = '';
                    //将所选中的Id全部都拼接成一个string
                    for (var i = 0; i < rows.length; i++) {
                        strId += rows[i].ID + ',';
                    }
                    strId = strId.substr(0, strId.length - 1);
                    $.post('/UserInfo/DeleteUserInfo', { "strId": strId }, function (data) {
                        if (data=="ok") {
                            $('#tt').datagrid('clearSelections');
                            $('#tt').datagrid('reload');
                            $.messager.show({
                                title: '提示',
                                msg: '删除成功',
                                showType: 'show'
                            });
                        }
                        else {
                            $.messager.alert("提示", "删除失败", "error");
                        }
                    })
                }
            });


        }

        //单击修改操作，渲染修改模块
        function editInfo() {
            //判断用户选择是否符合规则
            var rows = $('#tt').datagrid('getSelections');
            if (rows.length != 1) {
                $.messager.alert("提醒", "请选择一条数据，不能多选也不能不选!", "error");
                return;
            }
            //发送异步请求，得到要修改的数据，赋值到修改模块中
            $.post("/UserInfo/GetUserInfoModel", { "id": rows[0].ID }, function (data) {
                $("#txtUName").val(data.UName);
                $("#txtUPwd").val(data.UPwd);
                $("#txtRemark").val(data.Remark);
                $("#txtSort").val(data.Sort);
                $("#txtID").val(data.ID);
                $("#txtSubTime").val(ChangeDateFormat(data.SubTime));
            });
            //显示出修改数据的版块
            $("#divEdit").css("display", "block");
            $('#divEdit').dialog({
                title: "修改信息",
                collapsible: true,
                width: 300,
                height: 400,
                modal: true,
                resizable: true,
                buttons: [{
                    text: '确定',
                    iconCls: 'icon-ok',
                    handler: function () {
                        //提交表单
                        $("#editForm").submit();
                    }
                }, {
                    text: '取消',
                    handler: function () {
                        $('#divEdit').dialog('close');
                    }
                }]
            });
        }

        //提交修改表单之后的操作
        function afterEdit(data) {
            if (data == "ok") {
                $('#divEdit').dialog('close');
                $('#tt').datagrid('clearSelections');
                $('#tt').datagrid('reload');
                $.messager.show({
                    title: '提示',
                    msg: '修改成功',
                    showType: 'show'
                });
            } else {
                $.messager.alert("提醒", "修改失败!", "error");
            }
        }

        //将序列化成json格式后日期(毫秒数)转成日期格式
        function ChangeDateFormat(cellval) {
            var date = new Date(parseInt(cellval.replace("/Date(", "").replace(")/", ""), 10));
            var month = date.getMonth() + 1 < 10 ? "0" + (date.getMonth() + 1) : date.getMonth() + 1;
            var currentDate = date.getDate() < 10 ? "0" + date.getDate() : date.getDate();
            return date.getFullYear() + "-" + month + "-" + currentDate;
        }
    </script>
</head>
<body>
    <table id="tt" style="width: 700px;" title="标题，可以使用代码进行初始化，也可以使用这种属性的方式" iconcls="icon-edit"></table>

    <!-------------------------------------------------------------添加数据开始-------------------------------------------------------------------->
    <div id="divAdd">
        @using (Ajax.BeginForm("AddUserInfo", "UserInfo", new { }, new AjaxOptions() { HttpMethod = "post", OnSuccess = "afterAdd" }, new { id = "addForm" }))
        {
            <table>
                <tr><td>用户名</td><td><input type="text" name="UName" /></td></tr>
                <tr><td>密码</td><td><input type="text" name="UPwd" /></td></tr>
                <tr><td>备注</td><td><input type="text" name="Remark" /></td></tr>
                <tr><td>排序</td><td><input type="text" name="Sort" /></td></tr>
            </table>
        }
    </div>
    <!-------------------------------------------------------------添加数据结束-------------------------------------------------------------------->
    <!-------------------------------------------------------------修改数据开始-------------------------------------------------------------------->
    <div id="divEdit">
        @using (Ajax.BeginForm("EditUserInfo", "UserInfo", new { }, new AjaxOptions() { HttpMethod = "post", OnSuccess = "afterEdit" }, new { id = "editForm" }))
        {
            <input type="hidden" name="SubTime" id="txtSubTime" />
            <input type="hidden" name="ID" id="txtID" />
            <table>
                <tr><td>用户名</td><td><input type="text" name="UName" id="txtUName" /></td></tr>
                <tr><td>密码</td><td><input type="text" name="UPwd" id="txtUPwd" /></td></tr>
                <tr><td>备注</td><td><input type="text" name="Remark" id="txtRemark" /></td></tr>
                <tr><td>排序</td><td><input type="text" name="Sort" id="txtSort" /></td></tr>
            </table>
        }
    </div>
    <!-------------------------------------------------------------修改数据开始-------------------------------------------------------------------->

    <!-------------------------------------------------------------分配角色信息开始-------------------------------------------------------------------->
    <div id="setRoleDiv">
        <iframe id="setRoleFrame" frameborder="0" scrolling="no" width="100%" height="100%"></iframe>
    </div>
    <!-------------------------------------------------------------分配角色信息开始-------------------------------------------------------------------->

    <!-------------------------------------------------------------分配权限信息开始-------------------------------------------------------------------->
    <div id="setActionDiv" style="overflow:hidden">
        <iframe id="setActionFrame" frameborder="0" scrolling="auto" width="100%" height="100%"></iframe>
    </div>

    <!-------------------------------------------------------------分配权限信息结束-------------------------------------------------------------------->



</body>
</html>

ZHJ.PerfectOA.WebApp/Views/UserInfo/SetUserActionInfo.cshtml
@{
    Layout = null;
}

@using ZHJ.PerfectOA.Model
@model ZHJ.PerfectOA.Model.UserInfo
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SetUserActionInfo</title>
    <link href="~/Content/themes/default/easyui.css" rel="stylesheet" />
    <link href="~/Content/themes/icon.css" rel="stylesheet" />
    <link href="~/Content/tableStyle.css" rel="stylesheet" />
    
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.easyui.min.js"></script>
    <script src="~/Scripts/easyui-lang-zh_CN.js"></script>
    <script type="text/javascript">
        $(function () {
            $(".selectActions").click(function () {
               // var userId=
                $.post("/UserInfo/SetUserActionInfo", {
                    "userId": "@Model.ID", "actionId": $(this
                    ).attr("ids"),"value":$(this).val()}, function (data) {
                        if (data == "ok") {
                            $.messager.show({
                                title: '提示',
                                msg: '分配成功',
                                showType: 'show'
                            });
                        }
                        else {
                            $.messager.show({
                                title: '提示',
                                msg: '分配失败!!',
                                showType: 'show'
                            });
                        }
                });
            });
            $(".btnClear").click(function () {
                var $control = $(this);
                $.post("/UserInfo/RemoveUserAction", {
                    "userId": "@Model.ID", "actionId": $(this
                        ).attr("ids")
                }, function (data) {
                    if (data == "ok") {
                        $control.parent().find(".selectActions").removeAttr("checked");
                        $.messager.show({
                            title: '提示',
                            msg: '清除成功',
                            showType: 'show'
                        });
                    }
                    else {
                        $.messager.show({
                            title: '提示',
                            msg: '清除失败!!',
                            showType: 'show'
                        });
                    }
                });
            });


        });

    </script>

</head>
<body>
    <div>
        为用户
        @{
            <span style="font-size:16px;color:red">@Model.UName</span>
        }分配权限

        <table>
            <tr><th>权限编号</th><th>权限名称</th><th>地址</th><th>请求方式</th><th>操作</th></tr>
            @using (Ajax.BeginForm("SetUserActionInfo", "UserInfo", new { }, new AjaxOptions() { }, new { id = "setActionForm" }))
            {

                List<ActionInfo> actionInfoList = ViewBag.AllActionInfo;
                List<R_UserInfo_ActionInfo> r_userInfo_ActionInfoList = ViewBag.AllActionId;
                foreach (ActionInfo actionInfo in actionInfoList)
                {
                    <tr>
                        <td>@actionInfo.ID</td>
                        <td>@actionInfo.ActionInfoName</td>
                        <td>@actionInfo.Url</td>
                        <td>@actionInfo.HttpMethod</td>
                        <td>
                            @{
                    var rb = "rb_" + actionInfo.ID;
                    //var norb = "norb_" + actionInfo.ID;
                    var isExt = (from r in r_userInfo_ActionInfoList
                                 where r.ActionInfoID == actionInfo.ID
                                 select r).FirstOrDefault();
                    if (isExt != null)
                    {
                        if (isExt.IsPass == true)
                        {
                            <label for="@rb">允许</label>
                                <input type="radio" name="@rb" checked="checked" ids="@actionInfo.ID" class="selectActions" value="true" />
                                <label for="@rb">拒绝</label>
                                <input type="radio" name="@rb" ids="@actionInfo.ID" class="selectActions" value="false" />
                        }
                        else
                        {
                            <label for="@rb">允许</label>
                                <input type="radio" name="@rb" ids="@actionInfo.ID" class="selectActions" value="true" />
                                <label for="@rb">拒绝</label>
                                <input type="radio" name="@rb" checked="checked" ids="@actionInfo.ID" class="selectActions" value="false" />
                        }
                    }
                    else
                    {
                        <label for="@rb">允许</label>
                                <input type="radio" name="@rb" ids="@actionInfo.ID" class="selectActions" value="true" />
                                <label for="@rb">拒绝</label>
                                <input type="radio" name="@rb" ids="@actionInfo.ID" class="selectActions" value="false" />
                    }
                    <input type="button" value="清除" class="btnClear" ids="@actionInfo.ID" />
                            }

                        </td>
                    </tr>
                }


            }
        </table>

    </div>

</body>
</html>

ZHJ.PerfectOA.WebApp/Views/UserInfo/SetUserRoleInfo.cshtml
@{
    Layout = null;
}
@using ZHJ.PerfectOA.Model
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SetUserRoleInfo</title>
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script type="text/javascript">
        function subForm() {
            //提交表单
            $("#setRoleForm").submit();
        }
        //调用父窗体中的afterSetUserRole方法
        function afterSet(data) {
            if (data == "ok") {
                window.parent.afterSetUserRole();
            }
        }
    </script>
</head>
<body>
    为 @{
        UserInfo userInfo = ViewBag.UserInfo;
        <span style="font-size:16px;color:red"> @userInfo.UName</span>
    } 分配角色
    @using (Ajax.BeginForm("SetUserRoleInfo", "UserInfo", new { }, new AjaxOptions() { HttpMethod = "post", OnSuccess = "afterSet" }, new { id = "setRoleForm" }))
    {
        <input type="hidden" name="userId" value="@userInfo.ID" />
        List<RoleInfo> roleInfoList = ViewBag.AllRole;
        List<int> roleIdList = ViewBag.AllRoleId;
        foreach (RoleInfo roleInfo in roleInfoList)
        {
            var roleName = "cba_" + roleInfo.ID;
            if (roleIdList.Contains(roleInfo.ID))
            {
                <input type="checkbox" name="@roleName" checked="checked" value="@roleInfo.ID" />@roleInfo.RoleName
            }
            else
            {
                <input type="checkbox" name="@roleName" value="@roleInfo.ID" />@roleInfo.RoleName
            }
        }
    }

</body>
</html>